name: Run E2E tests
on:
  push:
    branches:
      - smoke-testing
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: "${{ ( github.event_name == 'pull_request' ) ||  github.event_name == 'push' }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [ '@general', '@cashapp', '@sync', '@giftcard' ]
    env:
      WP_ADMIN_USERNAME: ${{ secrets.WP_ADMIN_USERNAME }}
      WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
      SQUARE_APPLICATION_ID: ${{ secrets.SQUARE_APPLICATION_ID }}
      SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
      SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
      GH_TOKEN: ${{ secrets.ORG_DOWNLOADS }}
    permissions:
      pull-requests: write
    name: E2E tests (${{ matrix.type }})
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: '7.4'
          tools: composer:v2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Install Node dependencies
        run: npm ci && npm run build

      - name: Install playwright
        run: npx playwright install --with-deps chromium

      # Use compiled versions to avoid need for npm and composer installation and build step.
      - name: Install required WP plugins
        run: |
          gh release download --repo woocommerce/woocommerce-pre-orders --pattern  woocommerce-pre-orders.zip --dir ./test-plugins
          gh release download --repo woocommerce/woocommerce-subscriptions --pattern  woocommerce-subscriptions.zip --dir ./test-plugins
          cd ./test-plugins
          unzip -o woocommerce-pre-orders.zip
          unzip -o woocommerce-subscriptions.zip
          cd ..

      - name: Set the core version
        if: "${{ contains(github.event.pull_request.labels.*.name, 'needs: WP RC test') }}"
        id: run-rc-test
        run: ./tests/bin/set-core-version.js WordPress/WordPress#master

      - name: Setup E2E environment
        run: npm run env:start

      - name: Run E2E tests
        id: square_e2e_tests
        if: ${{ github.event_name == 'pull_request' && matrix.type != '@general' }}
        run: npm run test:e2e -- --grep ${{ matrix.type }}

      - name: Run E2E tests (General)
        id: square_e2e_tests_general
        if: ${{ github.event_name == 'pull_request' && matrix.type == '@general' }}
        run: npm run test:e2e -- --grep-invert "@cashapp|@sync|@giftcard"

      - name: Run E2E Smoke Test
        if: ${{ github.event_name == 'push' && matrix.type != '@general' }}
        run: npm run test:e2e -- --grep ${{ matrix.type }}

      - name: Run E2E Smoke Test (General)
        if: ${{ github.event_name == 'push' && matrix.type == '@general' }}
        run: npm run test:e2e -- --grep-invert "@cashapp|@sync|@giftcard"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report-${{ matrix.type }}
          path: tests/e2e/test-results/report
          retention-days: 2
          if-no-files-found: ignore
