name: ESLint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup node and npm cache
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
          node-version-file: .nvmrc
          cache: npm

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      with:
          files: |
            **/*.js

    - name: Install Node dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npm ci

    - name: Run ESLint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npx wp-scripts lint-js ${{ steps.changed-files.outputs.all_changed_files }}
