name: ESLint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup node and npm cache
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
          node-version-file: .nvmrc
          cache: npm

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
      with:
          files: |
            **/*.js

    - name: Install Node dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npm ci

    - name: Run ESLint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npx wp-scripts lint-js ${{ steps.changed-files.outputs.all_changed_files }}
