name: 'WordPress Plugin Checks'
on: # rebuild any PRs and main branch changes
  push:
    branches:
    - trunk
    - develop

  pull_request:
    branches:
      - trunk
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run plugin check
      uses: wordpress/plugin-check-action@10857da14b6c2246d15402b3e69f777edcf8c12e # v1.1.9
      with:
        exclude-checks: |
          plugin_readme
          plugin_updater
          file_type
          trademarks
          direct_db_queries
          performant_wp_query_params
          enqueued_scripts_in_footer
          plugin_header_text_domain

        exclude-directories: |
          .github
          node_modules
          vendor
          tests
          bin
          build
          build
          assets

        exclude-files: |
          .eslintignore
          .eslintrc.js
          .gitignore
          .nvmrc
          .gitattributes
          .phpcs.xml.dist
          .wp-env.json
          .prettierrc.js
          .stylelintrc.json

        ignore-warnings: true
